--select * from [dbo].[TblAccount]
--select * from [dbo].[TblAccountHierarchy]
--select * from [dbo].[TblAccountType]
--select * from [dbo].[TblActivity]
--select * from [dbo].[TblActivityNotify]
--select * from [dbo].[TblAddress]
--select * from [dbo].[TblAddressContact]
--select * from [dbo].[TblAddressEmployee]

---- select * from [dbo].[TblCity]
--select * from [dbo].[TblContact]
--select * from [dbo].[TblContactRole]
----select * from [dbo].[TblCountry]
--select * from [dbo].[TblDepartment]
--select * from [dbo].[TblDocument]
----select * from [dbo].[TblEmpHierarchy]
--select * from [dbo].[TblEmployee]
--select * from [dbo].[TblEmployeeRole]
--select * from [dbo].[TblEmployeeTarget]

--select * from [dbo].[TblEmpTask]
--select * from [dbo].[TblFinancialYear]
--select * from [dbo].[TblIncentive]
--select * from [dbo].[TblIndustry]
----select * from [dbo].[TblLanguage]
--select * from [dbo].[TblLead]
--select * from [dbo].[TblLeadContact]
--select * from [dbo].[TblLeadSource]
--select * from [dbo].[TblLocation]
--select * from [dbo].[TblLogin]
--select * from [dbo].[TblLoginHistory]
--select * from [dbo].[TblMileStone]
----select * from [dbo].[TblMileStoneStage]
--select * from [dbo].[TblModule]
--select * from [dbo].[TblModuleConfig]
--select * from [dbo].[TblOrgHierarchy]
--select * from [dbo].[TblOrgHierarchyNew]
--select * from [dbo].[TblOwnership]
--select * from [dbo].[TblParentAccount]
--select * from [dbo].[TblProduct]
----select * from [dbo].[TblProductType]
--select * from [dbo].[TblSetting]
----select * from [dbo].[TblState]
--select * from [dbo].[TblTranAccAdd]
--select * from [dbo].[TblTranLeadContact]
--select * from [dbo].[TblTransactionInfo]
--select * from [dbo].[TblTransContact]
--select * from [dbo].[TblTransDocument]
----select * from [dbo].[TblTransEmployeeTarget]
--select * from [dbo].[TblTransETask]
--select * from [dbo].[TblTransInfoDocumet]
--select * from [dbo].[TblTransLead]
--select * from [dbo].[TblTransLeadCompetitor]
--select * from [dbo].[TblTransLeadPriceDiscount]
--select * from [dbo].[TblUser]
--select * from [dbo].[TblUserAddress]


--select * from [dbo].[TblCity]
--select * from [dbo].[TblCountry]
--select * from [dbo].[TblEmpHierarchy]
--select * from [dbo].[TblLanguage]
--select * from [dbo].[TblMileStoneStage]
--select * from [dbo].[TblProductType]
--select * from [dbo].[TblState]
--select * from [dbo].[TblTransEmployeeTarget]



