//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIMBOLE.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NimboleStagingEntities1 : DbContext
    {
        public NimboleStagingEntities1()
            : base("name=NimboleStagingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAccount> TblAccounts { get; set; }
        public virtual DbSet<TblAccountHierarchy> TblAccountHierarchies { get; set; }
        public virtual DbSet<TblAccountType> TblAccountTypes { get; set; }
        public virtual DbSet<TblActivity> TblActivities { get; set; }
        public virtual DbSet<TblActivityNotify> TblActivityNotifies { get; set; }
        public virtual DbSet<TblAddress> TblAddresses { get; set; }
        public virtual DbSet<TblAddressContact> TblAddressContacts { get; set; }
        public virtual DbSet<TblAddressEmployee> TblAddressEmployees { get; set; }
        public virtual DbSet<TblCity> TblCities { get; set; }
        public virtual DbSet<TblCityNew> TblCityNews { get; set; }
        public virtual DbSet<TblContact> TblContacts { get; set; }
        public virtual DbSet<TblContactRole> TblContactRoles { get; set; }
        public virtual DbSet<TblCountry> TblCountries { get; set; }
        public virtual DbSet<TblCountryNew> TblCountryNews { get; set; }
        public virtual DbSet<TblDepartment> TblDepartments { get; set; }
        public virtual DbSet<TblDocument> TblDocuments { get; set; }
        public virtual DbSet<TblEmpHierarchy> TblEmpHierarchies { get; set; }
        public virtual DbSet<TblEmpHierarchyNew> TblEmpHierarchyNews { get; set; }
        public virtual DbSet<TblEmployee> TblEmployees { get; set; }
        public virtual DbSet<TblEmployeeRole> TblEmployeeRoles { get; set; }
        public virtual DbSet<TblEmployeeTarget> TblEmployeeTargets { get; set; }
        public virtual DbSet<TblEmpTask> TblEmpTasks { get; set; }
        public virtual DbSet<TblFinancialYear> TblFinancialYears { get; set; }
        public virtual DbSet<TblIncentive> TblIncentives { get; set; }
        public virtual DbSet<TblIndustry> TblIndustries { get; set; }
        public virtual DbSet<TblLanguage> TblLanguages { get; set; }
        public virtual DbSet<TblLanguageNew> TblLanguageNews { get; set; }
        public virtual DbSet<TblLead> TblLeads { get; set; }
        public virtual DbSet<TblLeadContact> TblLeadContacts { get; set; }
        public virtual DbSet<TblLeadSource> TblLeadSources { get; set; }
        public virtual DbSet<TblLocation> TblLocations { get; set; }
        public virtual DbSet<TblLogin> TblLogins { get; set; }
        public virtual DbSet<TblLoginHistory> TblLoginHistories { get; set; }
        public virtual DbSet<TblMileStone> TblMileStones { get; set; }
        public virtual DbSet<TblMileStoneStage> TblMileStoneStages { get; set; }
        public virtual DbSet<TblMileStoneStageNew> TblMileStoneStageNews { get; set; }
        public virtual DbSet<TblModule> TblModules { get; set; }
        public virtual DbSet<TblModuleConfig> TblModuleConfigs { get; set; }
        public virtual DbSet<TblOrgHierarchy> TblOrgHierarchies { get; set; }
        public virtual DbSet<TblOrgHierarchyNew> TblOrgHierarchyNews { get; set; }
        public virtual DbSet<TblOwnership> TblOwnerships { get; set; }
        public virtual DbSet<TblParentAccount> TblParentAccounts { get; set; }
        public virtual DbSet<TblProduct> TblProducts { get; set; }
        public virtual DbSet<TblProductType> TblProductTypes { get; set; }
        public virtual DbSet<TblProductTypeNew> TblProductTypeNews { get; set; }
        public virtual DbSet<TblSetting> TblSettings { get; set; }
        public virtual DbSet<TblState> TblStates { get; set; }
        public virtual DbSet<TblStateNew> TblStateNews { get; set; }
        public virtual DbSet<TblTranAccAdd> TblTranAccAdds { get; set; }
        public virtual DbSet<TblTranLeadContact> TblTranLeadContacts { get; set; }
        public virtual DbSet<TblTransactionInfo> TblTransactionInfoes { get; set; }
        public virtual DbSet<TblTransContact> TblTransContacts { get; set; }
        public virtual DbSet<TblTransDocument> TblTransDocuments { get; set; }
        public virtual DbSet<TblTransEmployeeTarget> TblTransEmployeeTargets { get; set; }
        public virtual DbSet<TblTransEmployeeTargetNew> TblTransEmployeeTargetNews { get; set; }
        public virtual DbSet<TblTransETask> TblTransETasks { get; set; }
        public virtual DbSet<TblTransInfoDocumet> TblTransInfoDocumets { get; set; }
        public virtual DbSet<TblTransLead> TblTransLeads { get; set; }
        public virtual DbSet<TblTransLeadCompetitor> TblTransLeadCompetitors { get; set; }
        public virtual DbSet<TblTransLeadPriceDiscount> TblTransLeadPriceDiscounts { get; set; }
        public virtual DbSet<TblUser> TblUsers { get; set; }
        public virtual DbSet<TblUserAddress> TblUserAddresses { get; set; }
        public virtual DbSet<VWAccountExport> VWAccountExports { get; set; }
        public virtual DbSet<VWAccountIndex> VWAccountIndexes { get; set; }
        public virtual DbSet<VWActivityMileStone> VWActivityMileStones { get; set; }
        public virtual DbSet<VWContactExport> VWContactExports { get; set; }
        public virtual DbSet<VWEmpActivityNotify> VWEmpActivityNotifies { get; set; }
        public virtual DbSet<VWEmployeeTarget> VWEmployeeTargets { get; set; }
        public virtual DbSet<VWLeadLsEmp> VWLeadLsEmps { get; set; }
        public virtual DbSet<VWLgnEmployee> VWLgnEmployees { get; set; }
        public virtual DbSet<VWLoginEmployee> VWLoginEmployees { get; set; }
        public virtual DbSet<VWProductExport> VWProductExports { get; set; }
        public virtual DbSet<VWTranDocument> VWTranDocuments { get; set; }
        public virtual DbSet<VWTrnContactAccount> VWTrnContactAccounts { get; set; }
        
    }
}
