//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIMBOLE.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblActivity()
        {
            this.TblActivityNotifies = new HashSet<TblActivityNotify>();
            this.TblTransLeads = new HashSet<TblTransLead>();
        }
    
        public long Id { get; set; }
        public System.Guid TenantId { get; set; }
        public Nullable<long> MileStoneId { get; set; }
        public string Title { get; set; }
        public string Type_A_E_M { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> RequireNotify { get; set; }
        public long ReferenceId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual TblMileStone TblMileStone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblActivityNotify> TblActivityNotifies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTransLead> TblTransLeads { get; set; }
    }
}
