//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIMBOLE.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblAccount()
        {
            this.TblLeads = new HashSet<TblLead>();
            this.TblTranAccAdds = new HashSet<TblTranAccAdd>();
        }
    
        public long Id { get; set; }
        public System.Guid TenantId { get; set; }
        public string Code { get; set; }
        public string AccountName { get; set; }
        public string AccountOwner { get; set; }
        public string AccountClassification { get; set; }
        public string ParentAccount { get; set; }
        public Nullable<long> Employees { get; set; }
        public string OwnerShip { get; set; }
        public string Industry { get; set; }
        public string AccountType { get; set; }
        public Nullable<bool> IsParentAccount { get; set; }
        public string DistributerName { get; set; }
        public string Subsidiary { get; set; }
        public string Region { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Rating { get; set; }
        public string SICCode { get; set; }
        public Nullable<long> AnnualRevenue { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLead> TblLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTranAccAdd> TblTranAccAdds { get; set; }
    }
}
