//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIMBOLE.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOrgHierarchyNew
    {
        public long Id { get; set; }
        public System.Guid TenantId { get; set; }
        public string Description { get; set; }
        public Nullable<long> Node_Id { get; set; }
        public Nullable<long> Under_Parent { get; set; }
        public Nullable<long> Level_Depth { get; set; }
    }
}
