//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIMBOLE.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTransEmployeeTarget
    {
        public long Id { get; set; }
        public Nullable<long> EmpId { get; set; }
        public Nullable<long> EmployeeRoleId { get; set; }
        public Nullable<long> FinancialYearId { get; set; }
        public Nullable<decimal> TargetHike { get; set; }
        public Nullable<bool> IsAutomatic { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<decimal> QuarterlyTarget { get; set; }
        public Nullable<decimal> MonthlyTarget { get; set; }
        public Nullable<decimal> WeeklyTarget { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
