//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIMBOLE.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTranLeadContact
    {
        public long Id { get; set; }
        public System.Guid TenantId { get; set; }
        public Nullable<long> LeadId { get; set; }
        public Nullable<long> ContactId { get; set; }
        public Nullable<long> ContactRoleId { get; set; }
    
        public virtual TblContact TblContact { get; set; }
        public virtual TblContactRole TblContactRole { get; set; }
        public virtual TblLead TblLead { get; set; }
    }
}
