//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIMBOLE.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTransactionInfo
    {
        public long Id { get; set; }
        public System.Guid TenantId { get; set; }
        public long LeadId { get; set; }
        public string TransactionName { get; set; }
        public string Address { get; set; }
        public string PlateNo { get; set; }
        public string ObjectId { get; set; }
        public string BPKBNumber { get; set; }
        public long TenorScheme { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
