//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIMBOLE.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTransETask
    {
        public long Id { get; set; }
        public System.Guid TenantId { get; set; }
        public long EmpTaskId { get; set; }
        public long TaskGivenToId { get; set; }
    
        public virtual TblEmployee TblEmployee { get; set; }
        public virtual TblEmpTask TblEmpTask { get; set; }
    }
}
