//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIMBOLE.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTransLeadPriceDiscount
    {
        public long Id { get; set; }
        public System.Guid TenantId { get; set; }
        public Nullable<long> LeadId { get; set; }
        public Nullable<System.DateTime> DiscountedDate { get; set; }
        public Nullable<decimal> DiscountedPrice { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual TblLead TblLead { get; set; }
    }
}
