//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIMBOLE.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWAccountExport
    {
        public long Id { get; set; }
        public System.Guid TenantId { get; set; }
        public string AccountCode { get; set; }
        public string AccountName { get; set; }
        public string AccountOwner { get; set; }
        public string AccountClassification { get; set; }
        public string ParentAccount { get; set; }
        public string ParentAccountName { get; set; }
        public Nullable<long> Employees { get; set; }
        public string OwnerShip { get; set; }
        public string OwnerShipName { get; set; }
        public string Industry { get; set; }
        public string IndustryName { get; set; }
        public string AccountType { get; set; }
        public string AccountTypeDescription { get; set; }
        public Nullable<bool> IsParentAccount { get; set; }
        public string Distributer { get; set; }
        public string DistributerName { get; set; }
        public string Subsidiary { get; set; }
        public string Region { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Rating { get; set; }
        public string SICCode { get; set; }
        public Nullable<long> AnnualRevenue { get; set; }
        public string Website { get; set; }
        public Nullable<bool> Status { get; set; }
        public string HouseNo { get; set; }
        public string StreetName { get; set; }
        public string Address_Type { get; set; }
        public Nullable<long> CountryId { get; set; }
        public string CountryName { get; set; }
        public Nullable<long> StateId { get; set; }
        public string StateName { get; set; }
        public Nullable<long> CityId { get; set; }
        public string CityName { get; set; }
        public string ZipCode { get; set; }
    }
}
