//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIMBOLE.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWActivityMileStone
    {
        public Nullable<long> Id { get; set; }
        public Nullable<long> LeadId { get; set; }
        public string LeadTitle { get; set; }
        public string LeadDescription { get; set; }
        public Nullable<long> LeadOwnerId { get; set; }
        public long AccountId { get; set; }
        public System.Guid TenantId { get; set; }
        public string ActivityTitle { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string ActivityComments { get; set; }
        public Nullable<long> MileStoneId { get; set; }
        public string Descriptions { get; set; }
    }
}
