//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIMBOLE.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWContactExport
    {
        public long Id { get; set; }
        public System.Guid TenantId { get; set; }
        public Nullable<long> LeadSourceId { get; set; }
        public string LeadSourceName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string ContactImageURL { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Status { get; set; }
        public string WorkEmail { get; set; }
        public Nullable<long> AccountId { get; set; }
        public string AccountName { get; set; }
        public Nullable<long> ContactRoleId { get; set; }
        public string ContactRole { get; set; }
        public Nullable<long> AddressId { get; set; }
        public string StreetName { get; set; }
        public string HouseNo { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string HomePhone { get; set; }
        public string Fax { get; set; }
        public string SkypeName { get; set; }
        public string Address_Type { get; set; }
        public Nullable<long> CountryId { get; set; }
        public string CountryName { get; set; }
        public Nullable<long> StateId { get; set; }
        public string StateName { get; set; }
        public Nullable<long> CityId { get; set; }
        public string CityName { get; set; }
    }
}
