//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIMBOLE.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWLoginEmployee
    {
        public long Id { get; set; }
        public long Login { get; set; }
        public System.Guid TenantId { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<long> LoginId { get; set; }
        public long EmpRoleId { get; set; }
        public string Code { get; set; }
    }
}
