//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIMBOLE.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWProductExport
    {
        public long Id { get; set; }
        public System.Guid TenantId { get; set; }
        public string ProductCode { get; set; }
        public string ProductType { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Comments { get; set; }
        public string BarCode { get; set; }
        public string ManufacturerName { get; set; }
        public Nullable<System.DateTime> ManufacturerDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ProductTypeDes { get; set; }
    }
}
